name: Java CI

on: [push, pull_request]

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: 17
            - name: Build Skript
              run: ./gradlew nightlyRelease
            - name: Run test scripts
              run: ./gradlew skriptTest
            - name: Upload Nightly Build
              uses: actions/upload-artifact@v1
              if: success()
              with:
                  name: skript-nightly
                  path: build/libs/Skript-nightly.jar
